server:
  port: 8481

spring:
  application:
    name: gateway-service

  datasource:
    url: jdbc:postgresql://localhost:5432/dynamic_route
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none   # gateway only READS
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

#      routes:
#
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/users/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: userServiceCB
#                fallbackUri: forward:/fallback/users
#
#        - id: auth-service
#          uri: lb://SPRING-CLOUD-MASTERY   # <-- исправь это имя!
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - StripPrefix=1
#            - name: CircuitBreaker
#              args:
#                name: authServiceCB
#                fallbackUri: forward:/fallback/auth
#
#        - id: account-service
#          uri: lb://ACCOUNT-SERVICE
#          predicates:
#            - Path=/api/accounts/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO