server:
  port: 8481

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/users

        - id: auth-service
          uri: lb://SPRING-CLOUD-MASTERY
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCB
                fallbackUri: forward:/fallback/auth

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh