server:
  port: 8481

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

      routes:

        # === USER-SERVICE ===
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users, /api/users/, /api/users/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/users

        # === AUTH-SERVICE ===
        - id: auth-service
          uri: lb://SPRING-CLOUD-MASTERY
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authServiceCB
                fallbackUri: forward:/fallback/auth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost       # 🔥 ОБЯЗАТЕЛЬНО
    prefer-ip-address: false  # 🔥 Чтобы НЕ брать 192.168.X.X
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh,trace,env

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO

jwt:
  secret: pouaiScyrJ8GnN5hlvUBjdf7JTQQI/Ws8CMDgLmH8fs=